baseurl = "https://xumj2021.github.io/"


title = "Democratize Data For Insights"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
paginate = 20 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4

[params]
  baseurl = "https://xumj2021.github.io/"
  header_image = "https://science.nasa.gov/wp-content/uploads/2023/09/jpegpia15481-2.jpg"
  title = "Democratize Data For Insights"
  SEOTitle = "Mengjie's Blog"
  keyword = "Mengjie, Xu, Python, Stata, SAS, Econometrics, Accounting, Crawling"

  hyvor = false
  showtoc = true

  katex = true


  leancloud = true
  leancloud_app_id = '3P9jaIQ2NvKaz5vHlUzUD98r-MdYXbMMI'
  leancloud_app_key = 'XadtPSYxmWAQm9iUAyMCzHOG'

  googleAnalytics = "G-309KENXF47"

  pygmentsCodeFences = true
  pygmentsUseClasses = true
  PygmentsStyle = "monokailight"
 
  # Sidebar settings
  sidebar_about_description = "PhD from Frankfurt School of Finance and Management. I will join Duke University as an Assistant Professor in Accounting."
  sidebar_avatar = "https://fig-lianxh.oss-cn-shenzhen.aliyuncs.com/jmavatar.jpg"
  about_me = true

  #featured_tags = false
  #featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "https://cdn.pixabay.com/photo/2017/03/09/12/31/error-2129569_1280.jpg"
  title_404 = "The page is missing"

  omit_categories = false

  [[params.addtional_menus]]


  [params.social]
  rss            = true
  email          = "m.xu@fs.de"
  github         = "https://github.com/xumj2021"
  Twitter        = "https://twitter.com/xumj2021"
  linkedin       = "https://www.linkedin.com/in/mengjie-xu-37410712b/"
